# Generated by Django 5.0.14 on 2025-08-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('confidence', models.FloatField()),
                ('ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.ecosystem')),
            ],
        ),
    ]
