# Generated by Django 5.0.14 on 2025-08-29 16:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('metadata', models.JSONField()),
                ('capture_date', models.DateTimeField(auto_now_add=True)),
                ('ndvi_score', models.FloatField(null=True)),
                ('water_detection', models.JSONField(null=True)),
                ('biodiversity_analysis', models.JSONField(null=True)),
                ('ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.ecosystem')),
            ],
        ),
    ]
