# Generated by Django 5.0.14 on 2025-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
