# Generated by Django 5.0.14 on 2025-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_images_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='turbidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='vegetation_area_m2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='vegetation_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='water_area_m2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='water_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='drones/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
