# Generated by Django 5.0.14 on 2025-09-08 13:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_images_turbidity_images_vegetation_area_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosystem',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
