# Generated by Django 5.0.14 on 2025-10-13 21:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_ecosystem_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-capture_date']},
        ),
        migrations.AddField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='parent_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_images', to='monitoring.images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='capture_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='ecosystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monitoring.ecosystem'),
        ),
    ]
